id: I06DD04BD
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-26T15:35:59+00:00'
last_modified: '2022-06-08T13:44:23.477683+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1CZ1087
  title: མཁས་པ་ཆེན་པོ་ཙནྡྲའི་གསན་ཡིག་ཉེར་མཁོ
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    '4146':
      image_group_id: I1CZ1467
      title: ''
      total_pages: 20
      order: 1
      base_file: 4146.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
