id: P010456
initial_creation_type: ocr
created_at: 26/03/2020
last_modified_at: 25/11/2021
source_metadata:
  id: bdr:W1CZ1087
  title: མཁས་པ་ཆེན་པོ་ཙནྡྲའི་གསན་ཡིག་ཉེར་མཁོ
  author: ''
  volumes:
    2728866f691546508151b520b0710cee:
      image_group_id: I1CZ1467
      title: ''
      volume_number: 1
      total_pages: 20
      base_file: v001.txt
